#Global Properties -SVT
browser=chrome
env=svt
url=https://ui.freecrm.com/
username=akkunache.dhandhanadhan@mailinator.com
password=Freecrm.akku@123
implicitWait=20
pageloadTimeout=50
headless=false
explicitWait=20
author=akkunache.dhandhanadhan@mailinator.com
application=Free CRM
screenshotEachStepLogger=true