#Global Properties -SVT
browser=chrome
env=svt
url=https://ui.freecrm.com/
username=freecrm.rdg@mailinator.com
password=Freecrm.rdg@123
implicitWait=20
pageloadTimeout=50
headless=false
explicitWait=20
author=rahuldev.ghosh@freecrm.com
application=Free CRM
screenshotEachStepLogger=true