#Global Properties -SVT
browser=chrome
env=svt
url=https://ui.freecrm.com/
username=freecrm.rdg@mailinator.com
password=Freecrm.rdg@123
#username=akkunache.dhandhanadhan@mailinator.com
#password=Freecrm.akku@123
implicitWait=5
pageloadTimeout=50
headless=false
explicitWait=20
author=rahuldev.ghosh@freecrm.com
application=Free CRM
screenshotEachStepLogger=true
db.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
db.username=freecrm_svt
db.password=Freecrm.rdg@123